[package]
name = "tmp-krilla-svg-custom-metadata"
version = "0.9.0-rc.1"
description = "Temporary fork of krilla-svg (converting SVG files to PDF) with custom PDF metadata support."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
krilla = { workspace = true, features = ["raster-images"] }
usvg = { workspace = true }
tiny-skia = { workspace = true }
resvg = { workspace = true }
flate2 = { workspace = true }
fontdb = { workspace = true }
skrifa = { workspace = true }
smallvec = { workspace = true }
